name: Code Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, betterer
        run: |
          npm i
          npm run betterer
        env:
          CI: true
      - name: Get Committer Name
        if: failure()
        run: |
          echo "##[set-output name=username;]$(git show -s --format='%ae' ${{GITHUB_SHA}})"
        id: get_committer_name
      - name: Get Fart Name
        if: failure()
        run: |
          declare -a expressions=('aerosolized stool' 'after dinner mint' 'air' 'air attack' 'air biscuit' 'air monkey' 'air poop' 'anal acoustics' 'Anal announcement' 'anal escape of wind' 'anal emissions' 'anal oxide' 'anal retreat' 'anus evacuation' 'Arkansas barking spiders' 'ars musica' 'arse blast' 'ass dropping' 'backblast' 'backdoor trumpet' 'back draft' 'back end blow out' 'bae' 'barking rats' 'barking spiders' 'bean bombers' 'bean fumes' 'beaver leaver' 'beer fart' 'belching clown' 'big spit-up' 'bilabial fricative' 'blampf' 'blare-ass' 'Blat' 'blow-by' 'blow fish' 'blue angel' 'blue bomber' 'blue darts' 'blurp' 'bologna sandwich essence' 'boomper letters' 'bork' 'bottom burp' 'botty burp' 'botty cough' 'bram' "brewer's fart" 'brown-body radiation' 'brown haze' 'brown mist' 'brown speckled mallard' 'brownster' 'brun canard' 'bubblers' 'buck snort or bucksnort' 'bull snort' 'bum and flutter' 'bunsen burners' 'burners' 'burp that went astray' 'burp that comes out the wrong end' 'butt burps' 'butt cheek squeak' 'butt moose' 'butt mutt' 'Butt trumpet' "can o' chedder" 'carpet creeper' 'case of swamp ass' 'cheeser' 'cheese toasty' 'chert' 'chold' 'chou pi' 'chunder' 'churchhouse creepers' 'cornhole tremor' 'crepidus' 'crunchy frog' 'cushion creepers' 'davebrok' 'deer snort' 'dej' 'desert varnish' 'doofu' 'doozer' 'doozy' 'double flutterblast' 'drifters' 'drig' 'drive by' 'Dutch oven' 'eggy whiffo' 'essence of Emeril' 'excreted gas' 'explosion between the cheeks' 'extreme fumagatory essence' 'fang pae' 'fang pi' 'fannitosis' 'fanny beep' 'fanny bubble' 'fanny halitosis' 'fart' 'fartrogen dioxide' 'fat lady delight' 'fecal clouds' 'fickle fuzz' 'fing' 'fingi' 'fire in the hole' 'fizz' 'fizz-fuzz' 'fizzy fuzz' 'flabbergaster' 'flame throwers' 'flatulence' 'flatulencia' 'flatus' 'flooper' 'fluff' 'flurpies' 'fly breaking the sound barrier' 'foo-foo' 'frump' 'Furz' 'fuss' 'the fuzz' 'the fuzz=fizz' 'gas' 'gasser' 'gastronomical reprocussion' 'General Colon Bowel barking commands' 'gluteal tuba' 'gooz' 'gross wind' 'grosse humours' 'guano-talk' 'gou pi' 'grunghee' 'gurglers' 'hanger' 'hissers' 'hole in the wall gang' 'honksa' 'hot wind' 'Hun Futza' 'hurricane' 'hydrogen bombs' 'ignimbrite' 'Jersey torch' 'jetwash' 'kabooms' 'kanala' 'the leather cheerio bark' 'lingers' 'lort' 'love puff' 'low flying geese' 'low flying jets' 'massive vapor of butt gas' 'message from the interior' 'methane' 'misdirected burp' 'Missouri mud ducks' 'moon beam' 'morning thunder' 'mouse' 'mousie squeak' 'mudslapper' 'mush' 'musical butt' 'the nether belch' 'nuée ardent' 'one-cheek sneaks' 'One-gun salute' 'paad' 'pants geese' 'passed flatus' 'passed gas' 'peaches' 'pedo' 'peido' 'peo' 'pet' 'petard' 'phewie' 'pip' 'pluts' 'poelse' 'poodles' 'poof' 'poofume' 'poo gas' 'pooh' 'pooh noise' 'poop fumes' 'poop without the mess' 'poopy tunes' 'poot' 'pooty pants' 'popcorn fart' 'pop tarts' 'power poof' 'preets' 'prison break' 'proot-proots' 'prootsie' 'prut' 'pudd' 'puffer' 'puh' 'puk' 'pulpmiller' 'pum' 'purple clouds' 'putt-putts' 'queve' 'rames' 'rare arse' 'rattler' 'rectal turbulence' 'report' 'ringo' 'ringtailed roarer' 'rip ass' 'ripship' 'the ripshit' 'ripskin' 'ripsnorter' 'roevgas' 'Room clearer' 'rup rap' 'the scented scream' 'scheet' 'seam squirrels' 'shit fumes' 'shit propellant' 'shit vapor' 'shit without the mess' 'silent but deadly' 'silent but violent' 'silent depth charge' 'silent spadily' 'sitter air' 'Singe' 'skag' 'skid' 'sliders' 'smelly jelly' 'smell-o-rama' 'smelts' 'smoofer' 'snak' 'S.O.D.' 'some asshole behind you talking shit' 'sound spadily' 'sphincter whistle' 'sphincturbulence' 'spitters' 'squeakers' 'squib' 'stainer' 'stale wind' 'stench of death' 'stink' 'stinker' 'surprise' 'svaerd' 'talking pants' 'tear arse' 'tear ass' 'terminal flatulence' 'terminal velocity flatulence' 'three tone fart' 'thunder below' 'thunder in the buns' 'tonage' 'toop' 'tooters' 'toot-toots' 'triple flutter blaster' 'triple thunder flutter' 'trouser cough' 'trouser trumpet' 'trump' 'turtle' 'tushie belches' 'underpants lion' 'Under-thunder' 'veirnt' 'ventifact' 'vind' 'voice of the toothless one' 'wet fart' 'wet one' 'whallop' 'whootzie' 'wind' 'wind breakage' 'windy pops' 'wizard' 'zephyr')
          echo "##[set-output name=fartname;]${expressions[$RANDOM % ${#expressions[@]} ]}"
        id: get_fart_name
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#F44336"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Congratulate ${{steps.get_committer_name.outputs.username}}, that ${{steps.get_fart_name.outputs.fartname}}, for introducing crap into the conversation. :rocket:"
          SLACK_TITLE: Woo-Hoo.
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
