name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, betterer
        run: |
          npm i
          npm run betterer
        env:
          CI: true
      - name: blah
        if: failure()
        run: |
          echo "::set-env name=username::yellow"
      - name: Slack Notification
        # if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: "#3278BD"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "${{username}}, that fanny beep, introducing crap into the conversation. :rocket:"
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
